#pragma once

enum class Pattern
{	
	ReadyHand = 1,
	DoubleReady,
	OneShot,	
	LastTileFromTheWall,
	LastDiscard,
	DeadWallDraw,
	RobbingQuad,
	SelfDrawn,
	OneSetOfIdenticalSequences,
	NoPointsHand,
	WhiteDragon,
	GreenDragon,
	RedDragon,
	EastWind,
	SouthWind,
	WestWind,
	NorthWind,
	DoubleEastWind,
	DoubleSouthWind,
	DoubleWestWind,
	DoubleNorthWind,
	AllSimples,
	ThreeColourStraights,
	Straight,
	TerminalOrHonorInEachSet,
	SevenPairs,
	AllTriplets,
	ThreeClosedTriplets,
	ThreeColourTriplets,
	ThreeQuads,
	LittleThreeDragons,
	AllTerminalsAndHornors,
	HalfFlush,
	TwoSetsOfIdenticalSequences,
	TerminalInEachSet,
	Flush,

	// limit hands
	HeavenlyHand,
	EarthlyHand,
	FourClosedTriplets,
	ThirteenOrphans,
	NineGates,
	AllGreen,
	AllHonors,
	AllTerminals,
	BigThreeDragons,
	LittleFourWinds,
	BigFourWinds,
	FourQuads,
};
